name: diffusion
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.19
  - cudatoolkit=11.8
  - cudnn=8.7.0
  - h5py
  - pip
  - pip:
    - --index-url=https://download.pytorch.org/whl/cu118
    - torch==2.4.1+cu118
    - torchaudio==2.4.1+cu118
    - torchvision==0.19.1+cu118
    - flask
    - flask-cors
    - flask-socketio
    - pytest
    - pytest-asyncio
    - eventlet
    - matplotlib
    - aiohttp
    - imageio